### DISCUSSION TITLE
Gitalk in Organization GitHub Pages cannot find the issues.

### DISCUSSION THREAD

**Discussion by sandyzikun** [gitalk/gitalk#481] [Q&A] [answered]
## 组织账户的 GitHub Pages 上的 Gitalk 无法找到与创建对应的 issues

https://liella-gen2.github.io/2021/10/12/holax-sekai/

This is our organization blog, based on [Hexo](https://hexo.io/), using Gitalk, `liella-gen2` is the username of our GitHub-organization.

这是我们社团的blog，基于[Hexo](https://hexo.io/)搭建，`liella-gen2`是我们GitHub组织的用户名。

![image](https://user-images.githubusercontent.com/36362203/138662101-2403f13b-fcbe-46bc-98bd-26ad2182fd95.png)

I set my parameters like below, and enabled the issues of the repo. Nevertheless, it cannot find or create the issues.

我设置参数如下，对应的repo也开了issues。但是它找不到也无法创建issues。

`_config.yml`
```yml
gitalk:
  enabled: true
  owner: liella-gen2
  repo: liella-gen2.github.io
  admin: ["liella-gen2"]
  clientID: "..."
  clientSecret: "..."
  distractionFreeMode: false
```

`comments.ejs`
```ejs
<% if (page.comments) { %>
    <% if (theme.gitalk.enabled) { %>
        <div id="gitalk-container"></div>
        <script>
            var gitalk = new Gitalk({
                clientID: "<%= theme.gitalk.clientID %>",
                clientSecret: "<%= theme.gitalk.clientSecret %>",
                id: window.location.pathname,
                repo: "<%= theme.gitalk.repo %>",
                owner: "<%= theme.gitalk.owner %>",
                admin: "<%= theme.gitalk.admin %>",
                distractionFreeMode: "<%= theme.gitalk.distractionFreeMode %>"
            });
            gitalk.render('gitalk-container');
        </script>
    <% } %>
<% } %>
```

Hope somebody could help me ...

希望有人能帮我。。。
