### ISSUE TITLE
Error:Not Found

### ISSUE THREAD

**Issue by ZeddYu** [gitalk/gitalk#173]
https://api.github.com/repos/ZeddYu/ZeddYu.github.io/issues?client_id=3e937cfbdaf65b2cd0a4&client_secret=ee77d7f4138a39d33c56228d109e2693e5eb21f5&labels=Gitalk,%2F2018%2F04%2F13%2F%25E5%2587%25A0%25E9%2581%2593%25E9%25A2%2598%25E4%25B8%25AD%25E7%259A%2584%25E5%25AD%25A6%25E4%25B9%25A0%2F&t=1534477602889

看了一下请求发现是这个404了，然而我感觉自己配置并没有错误，api请求user是请求到了，地址是blog.zeddyu.info，找了很多相关的错误，都没有解决...

具体配置：
gitalk:
    clientID: 'xxxxxx'
    clientSecret: 'xxxxx'
    repo: 'ZeddYu.github.io'
    owner: 'ZeddYu'
    admin: ['ZeddYu']
    id: location.pathname
    distractionFreeMode: false

**Comment by ZeddYu** [comment]
@booxood 创建了。私有项目。Authorization callback URL已经设置为我自定义的域名https://zeddyu.info

**Comment by dearchill** [comment]
我也是这样，可以登录 GitHub 账号但无法评论，上方显示 Error: Not Found.

**Comment by CoderMing** [comment]
@ZeddYu 不支持私有项目。私有项目在没登陆的情况下是无法获取的，而gitalk本身抓数据是不带有登录信息的。

**Comment by dearchill** [comment]
@CoderMing 感谢！问题已解决

**Comment by booxood** [comment]
问题解决了就先关闭了 :tada::tada::tada:

**Comment by JD1412** [comment]
我的是不能够登录（404）并且评论区上方显示“Error: Not Found.”
我的配置文件如下：
```
gitalk:
  enable: true
  github_id: JD1412
  repo: github.com/JD1412/JD1412.github.io.git
  client_id: xxxxxxxxxxxxxxxx
  client_secret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  admin_user: ['JD1412']
  distraction_free_mode: true # Facebook-like distraction free mode
```
请问我的这个是什么问题啊？
