### ISSUE TITLE
报错：Error: i.concat(...).join is not a function

### ISSUE THREAD

**Issue by EatSleepDebug** [gitalk/gitalk#195]
## 问题描述
在按照教程配置部署之后，本地和线上都会报错：Error: i.concat(...).join is not a function

## 配置信息
```
{% if page.comments && theme.gitalk.enable %}

  <link rel="stylesheet" href="https://unpkg.com/gitalk/dist/gitalk.css">

  <script src="https://unpkg.com/gitalk/dist/gitalk.min.js"></script>

  <script type="text/javascript">
      var gitalk = new Gitalk({
        clientID: '{{ theme.gitalk.ClientID }}',
        clientSecret: '{{ theme.gitalk.ClientSecret }}',
        repo: '{{ theme.gitalk.repo }}',
        owner: '{{ theme.gitalk.owner }}',
        admin: ['{{ theme.gitalk.adminUser }}'],
        perPage: {{ theme.gitalk.perPage }},
        pagerDirection: '{{ theme.gitalk.pagerDirection }}'
      })
      gitalk.render('gitalk-container')           
  </script>

{% endif %}

```
```
gitalk:
  enable: true
  ClientID: 48dce994c65cfcda101d # MUST HAVE, Github client id for the Gitment
  ClientSecret: 4da0b467a5dffeb174f9787d3493307380775701 # EITHER this or proxy_gateway, Github access secret token for the Gitment
  repo: EatSleepDebug.github.io # MUST HAVE, The repo you use to store Gitment comments
  owner: EatSleepDebug # MUST HAVE, Your Github ID
  adminUser: EatSleepDebug # MUST HAVE, Your Github ID
  perPage: 10 #每页多少个评论
  pagerDirection: last #排序方式是从旧到新（first）还是从新到旧（last）
  # createIssueManually: true
```
```
开了强制https，回调也用了https
```
### 断点
![image](https://user-images.githubusercontent.com/35959679/47559580-7a728b80-d948-11e8-8196-1cf81ffdc062.png)
### 控制台
![image](https://user-images.githubusercontent.com/35959679/47559619-8f4f1f00-d948-11e8-856d-fabf3cc52f7e.png)
### 界面
![image](https://user-images.githubusercontent.com/35959679/47559654-a261ef00-d948-11e8-8d4a-d75aa2e6cfc4.png)
