### ISSUE TITLE
Gitalk 无法加载，提示 Error: Network error

### ISSUE THREAD

**Issue by iarchean** [gitalk/gitalk#241]
Gitalk 无法加载，在等待一段时间后提示 Network error，搞了一个多小时没有搞定，所以不得已上来提个 issue。

[博客地址](https://archeanz.com/2019/03/03/docker-learn-memo-1/)

使用的 Hexo，icarus 主题。配置：

```
comment:
    # Name of the comment plugin
    type: gitalk
    enable: true
    owner: iarchean  
    repo: iarchean.github.io   
    client_id: xxx
    client_secret: xxx
    admin: iarchean #指定可初始化评论账户
    distractionFreeMode: true

```
问题图片：

![](https://i.imgur.com/T27Rcyd.png)

但奇怪的是，我[另一个域名下的完全一样内容的博客](https://blog.archean.me)就可以正常加载。请问是什么原因？

**Comment by iarchean** [comment]
Gitalk 无法加载，在等待一段时间后提示 Network error，搞了一个多小时没有搞定，所以不得已上来提个 issue。

[博客地址](https://archeanz.com/2019/03/03/docker-learn-memo-1/)

使用的 Hexo，icarus 主题。配置：

```
comment:
    # Name of the comment plugin
    type: gitalk
    enable: true
    owner: iarchean  
    repo: iarchean.github.io   
    client_id: xxx
    client_secret: xxx
    admin: iarchean #指定可初始化评论账户
    distractionFreeMode: true

```
问题图片：

![](https://i.imgur.com/T27Rcyd.png)

但奇怪的是，我[另一个域名下的完全一样内容的博客](https://blog.archean.me)就可以正常加载。请问是什么原因？
