### ISSUE TITLE
Error:Not found

### ISSUE THREAD

**Issue by mike-box** [gitalk/gitalk#307]
NexT.utils.getScript('//cdn.jsdelivr.net/npm/gitalk@1/dist/gitalk.min.js', () => {
    var gitalk = new Gitalk({
      clientID: 'dda64f2a41bd6feeb1d5',
      clientSecret: 'c01e6b4451cfa1655deb691457873df4af8d41d1',
      repo: 'blogtalk',
      owner: '56879683',
      admin: ['mike-box'],
      id: 'fdea4bf1d1a6c211c30d24d5657270ad',
        language: '',
      distractionFreeMode: 'false'
    });
    gitalk.render('gitalk-container');
  }, window.Gitalk);
```
gitalk:
  enable: true
  github_id: mike-box # GitHub repo owner
  repo: blogtalk # Repository name to store issues
  client_id: 62708782911367e632e3 # GitHub Application Client ID
  client_secret: f12d6e86618ff3fd2599b155778cfbe5270fa048 # GitHub Application Client Secret
  admin_user: mike-box # GitHub repo owner and collaborators, only these guys can initialize gitHub issues
  distraction_free_mode: false # Facebook-like distraction free mode
  id: location.pathname
  # Gitalk's display language depends on user's browser or system environment
  # If you want everyone visiting your site to see a uniform language, you can set a force language value
  # Available values: en | es-ES | fr | ru | zh-CN | zh-TW
  language: en
```
还是老问题，没法通过啊。
