### ISSUE TITLE
私有仓库 与 hexo gitalk 与 加密博客

### ISSUE THREAD

**Issue by Hughshine** [gitalk/gitalk#342]
遇到了一些问题，刚刚解决，在这里给一下（权宜的）解决方案。
问题是：
1. 私有仓库的原因  Error: not found
2. gitalk将加密博客（hexo）公开

加密博客（存在加密文章）会使用私有仓库用于github pages。hexo-gitalk默认会复制原文作为issue body，相当于把文章公开了。这种情况建议不开启加密文章的gitalk。所以最好设置`createIssueManually: true`。由于有时允许文章不公开，评论无所谓，为这种情况再更改一下默认的issue body。

需要更改：
`hexo-matery-modified/themes/matery/layout/_partial/gitalk.ejs`，为
```
let gitalk = new Gitalk({
        clientID: '<%- theme.gitalk.oauth.clientId %>',
        clientSecret: '<%- theme.gitalk.oauth.clientSecret %>',
        repo: '<%- theme.gitalk.repo %>',
        owner: '<%- theme.gitalk.owner %>',
        admin: <%- JSON.stringify(theme.gitalk.admin) %>,
        body: '<%- theme.gitalk.body %>',
        id: '<%- page.path %>',
        createIssueManually: '<%- theme.gitalk.createIssueManually %>',
        distractionFreeMode: '<%- theme.gitalk.distractionFreeMode %>'  // Facebook-like distraction free mode
    });
```

然后再主题_config.yml中，做一下配置
```
gitalk: 
  enable: true 
  owner: owner 
  repo: blog-comments # 因为放置博客的仓库是私有的，需要创建一个公开仓库放置评论
  oauth: 
    clientId: <yourkey>
    clientSecret: <yoursecret>
  admin: owner
  body: "可以写上博客名，或者就写unknown"
  createIssueManually: true
  distractionFreeMode: true
```
此后，需要手动为每一篇博客启用评论功能。
