### ISSUE TITLE
css样式中 .gt-meta 的 z-index 值过大，导致层叠样式异常

### ISSUE THREAD

**Issue by LuckyRabbitFeet** [gitalk/gitalk#366]
![Snipaste_2020-03-09_21-41-16](https://user-images.githubusercontent.com/32757528/76218445-39ce9600-624f-11ea-9112-c16f1ba99c2b.png)
如图所示

“0条评论”和“未登录用户”层叠高于“标签”。

检查后发现“0条评论”、“未登录用户”的类选择器`.gt-meta`的`z-index`值为10。

个人认为在此处可以将`z-index`值设为0或1。

**Comment by RiddMa** [comment]
我也遇到此类问题，[博客里记录了一下](https://blog.riddma.com/ghost-cn-blog-add-gitalk/)，可供参考。

省流：
```css
.gt-container .gt-svg {
    width: 0.875em !important;
    height: 0.875em !important;
    vertical-align: text-top !important;
}

.gt-meta{
    z-index: 1 !important;
}

.gt-header{
    z-index: 0 !important;
}
```
