### ISSUE TITLE
改变Gitalk的主题颜色。

### ISSUE THREAD

**Issue by OrwillT** [gitalk/gitalk#376]
有没有自定义样式的选项可以修改Gitalk的主题颜色。因为蓝色和博客的主色调并不符合。

**Comment by Wangbaoqi** [comment]
同问

**Comment by OliverLew** [comment]
可以直接在浏览器inspector里找到元素，然后用css定制的吧，我在firefox上改了一下，是这样的：

![Screenshot_2020-05-02_11-43-35](https://user-images.githubusercontent.com/12032219/80854365-2dbcee80-8c6a-11ea-903b-d006a5a501b9.png)

当然不一定覆盖的很全，可以直接找原css（ https://cdn.jsdelivr.net/npm/gitalk@1/dist/gitalk.css ）。下面是火狐上导出来的修改css：

```css

/* gitalk.css | https://cdn.jsdelivr.net/npm/gitalk@1/dist/gitalk.css */

.gt-container .gt-btn {
  /* border: 1px solid #6190e8; */
  /* background-color: #6190e8; */
  border: 1px solid #619008;
  background-color: #619008;
}

.gt-container .gt-btn-preview {
  /* color: #6190e8; */
  color: #619008;
}

.gt-container .gt-header-controls-tip {
  /* color: #6190e8; */
  color: #619008;
}

.gt-container .gt-svg svg {
  /* fill: #6190e8; */
  fill: #619008;
}

.gt-container a:hover {
  /* color: #81a6ed; */
  /* border-color: #81a6ed; */
  color: #81a60d;
  border-color: #81a60d;
}

.gt-container .gt-link {
  /* border-bottom: 1px dotted #6190e8; */
  border-bottom: 1px dotted #619008;
}

.gt-container a {
  /* color: #6190e8; */
  color: #619008;
}

.gt-container .gt-popup .gt-action.is--active::before {
  /* background: #6190e8; */
  background: #619008;
}

.gt-container .gt-btn-preview:hover {
  /* border-color: #81a6ed; */
  border-color: #81a60d;
}

.gt-container .gt-user .is--poping .gt-ico svg {
  /* fill: #6190e8; */
  fill: #619008;
}

.gt-container .gt-btn-public:hover {
  /* background-color: #81a6ed; */
  /* border-color: #81a6ed; */
  background-color: #81a60d;
  border-color: #81a60d;
}

.gt-container .gt-comment-username {
  /* color: #6190e8; */
  color: #619008;
}
```
