### ISSUE TITLE
gitalk服务不稳定，有时能加载出来，有时加载不出来，有遇到过类似情况吗？

### ISSUE THREAD

**Issue by qisi007** [gitalk/gitalk#408]
这是我的配置，请问有什么问题吗

#  Developer settings 配置
###  Application name
liuguishengblog

### Homepage URL
https://www.liuguisheng.vip

###  Application description
刘贵生的博客评论

### Authorization callback URL
https://www.liuguisheng.vip

# _config.yml配置
```
gitalk:
  enable: true
  owner: qisi007
  admin: qisi007
  repo: qisi007.github.io
  ClientID: 手动马赛克
  ClientSecret: 手动马赛克
  labels: 'gitalk'
  distractionFreeMode: true
```
