### ISSUE TITLE
给用hexo的小伙伴一点福利

### ISSUE THREAD

**Issue by xiaomoinfo** [gitalk/gitalk#43]
# 在comments文件夹下新建一个文件 gitalk.ejs
```
<link rel="stylesheet" href="https://unpkg.com/gitalk/dist/gitalk.css">
<script src="https://yiyeti.cc/usr/themes/veryse/css/gitalk.min.js"></script>
<div id="gitalk-container"></div>
<script type="text/javascript">
    var gitalk = new Gitalk({
        clientID: '<%= theme.gitalk.clientID %>',
        clientSecret: '<%= theme.gitalk.clientSecret %>',
        id: window.location.pathname,
        repo: '<%= theme.gitalk.repo %>',
        owner: '<%= theme.gitalk.owner %>',
        admin: '<%= theme.gitalk.admin %>',
        distractionFreeMode: '<%= theme.gitalk.on %>'
    })
    gitalk.render('gitalk-container')
</script>
```

# 在配置文件 disqus 下面添加新的配置
```
gitalk:
  on: true
  owner: 你的github账户名
  repo: 你要作为评论系统的repo
  admin: ['github用户名']
  clientID: 你的clientId
  clientSecret: 你的clientSecret
```

# 在article.ejs里引用评论
```
<% if (!index && post.comments){ %>
<% if (theme.duoshuo.on) { %>
<%- partial('comments/duoshuo', {
    key: post.path,
    title: post.title,
    url: config.url + url_for(post.path),
}) %>
<% } else if (theme.changyan.on) { %>
<%- partial('comments/changyan') %>
<% } else if (theme.gitalk.on) { %>
<%- partial('comments/gitalk') %>
<% } else if (config.disqus_shortname) { %>
<%- partial('comments/disqus', {
    shortname: config.disqus_shortname
}) %>
<% } %>
```
