### ISSUE TITLE
font color is white when in dark mode

### ISSUE THREAD

**Issue by Dedicatus546** [gitalk/gitalk#503]
#### Gitalk 版本

1.7.2

#### 报错信息？

when in dark mode, the `color` in default style of `textarea` tag was triggered to `color: white;`, `gitalk.css` define `background-color: white` and not define `color: black`. i can't see it clearly.

![](https://user-images.githubusercontent.com/48575405/165725832-cce154cd-dbc7-49d3-8ef3-791700965bba.png)

![image](https://user-images.githubusercontent.com/48575405/165726051-65286734-6986-4c08-96e1-f1df880118eb.png)

if gitalk don't adapt dark mode. the simple way to fix it is to add `color: black` to the selecter of `.gt-container .gt-header-textarea` in `gitalk.css`.

```css
.gt-container .gt-header-textarea {
    adding: 0.75em;
    display: block;
    -webkit-box-sizing: border-box;
    box-sizing: border-box;
    width: 100%;
    min-height: 5.125em;
    max-height: 15em;
    border-radius: 5px;
    border: 1px solid rgba(0,0,0,0.1);
    font-size: 0.875em;
    word-wrap: break-word;
    resize: vertical;
    background-color: #f6f6f6;
    outline: none;
    -webkit-transition: all 0.25s ease;
    transition: all 0.25s ease;
    /* add */ 
    color: black;
}
```

and now it work well.

![image](https://user-images.githubusercontent.com/48575405/165727461-c6a1ec5f-cd7d-4e44-87e0-189e5beabe3b.png)

#### 浏览器版本？

chrome(100.0.4896.127)
